rest_config:
  post:
    sendNotification:
      controller: 'core\notification\NotificationController::sendNotification'
    registration:
      controller: 'core\registration\RegistrationController::incomingRegistration'
    alarmTrigger:
      controller: 'core\alarm\AlarmController::alarmTriggered'
  get:
    registration:
      controller: 'core\registration\RegistrationController::chubRegistration'