rest_config:
  post:
    sendNotification:
      controller: 'core\notification\NotificationController::sendNotification'
    registration:
      controller: 'core\registration\RegistrationController::incomingRegistration'
    alarmTrigger:
      controller: 'core\alarm\AlarmController::alarmTriggered'
    alarmStatusUpdate:
      controller: 'core\alarm\AlarmController::alarmStatusUpdate'
    notifyDeadModules:
      controller: 'core\deadmodule\DeadModuleController::notifyDeadModules'
  get:
    registration:
      controller: 'core\registration\RegistrationController::chubRegistration'